
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

# This workflow contains a single job called "build"
jobs:
  # The build job runs on an ubuntu-latest machine
  posel_1:
    name: Check if test_main.cpp exists
    runs-on: self-hosted
    steps:
      - uses: actions/upload-artifact@v4

      - name: Check if test_main.cpp exists
        run: |
          if [ ! -f test_mainn.cpp ]; then
            echo "test_main.cpp not found, exiting workflow"
            exit 1
          fi
          
          with:
          name: naloga_pred
          path: napaka.txt
  posel_2:
    name: test
    runs-on: self-hosted
    needs: posel_1
